src/Cake.Issues.DocFx/DocFxIssuesProviderAliases.cs
Add DocFxIssuesProviderTypeName alias
Fixes #2
=> (GH-2) Add DocFxIssuesProviderTypeName alias

src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx.Tests/packages.config, src/Cake.Issues.DocFx/Cake.Issues.DocFx.csproj, src/Cake.Issues.DocFx/packages.config
Build against Cake 0.26.0
Fixes #11
=> (GH-11) Build against Cake 0.26.0

src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx.Tests/packages.config, src/Cake.Issues.DocFx/Cake.Issues.DocFx.csproj, src/Cake.Issues.DocFx/packages.config
Update to Cake.Issues 0.2.0-beta0002 and XUnit 2.3.1
Fixes #9
=> (GH-9) Update to Cake.Issues 0.2.0-beta0003

src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx.Tests/DocFxProviderTests.cs, src/Cake.Issues.DocFx.Tests/packages.config, src/Cake.Issues.DocFx/Cake.Issues.DocFx.csproj, src/Cake.Issues.DocFx/DocFxIssuesProvider.cs, src/Cake.Issues.DocFx/packages.config
Update Cake.Issues to 0.3.0
Fixes #15
=> (GH-15) Update Cake.Issues to 0.3.0

tools/packages.config
Build with Cake 0.29.0
Fixes #21
=> (GH-21) Build with Cake 0.29.0

src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx.Tests/packages.config, src/Cake.Issues.DocFx/Cake.Issues.DocFx.csproj, src/Cake.Issues.DocFx/packages.config
Update to Cake.Issues 0.4.0-beta.1
Fixes #23
=> (GH-23) Update to Cake.Issues 0.4.0-beta.1

src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx.Tests/DocFxProviderFixture.cs, src/Cake.Issues.DocFx.Tests/DocFxProviderTests.cs, src/Cake.Issues.DocFx.Tests/DocFxSettingsTests.cs, src/Cake.Issues.DocFx.Tests/packages.config, src/Cake.Issues.DocFx/Cake.Issues.DocFx.csproj, src/Cake.Issues.DocFx/DocFxIssuesAliases.cs, src/Cake.Issues.DocFx/DocFxIssuesProvider.cs, src/Cake.Issues.DocFx/DocFxIssuesSettings.cs, src/Cake.Issues.DocFx/packages.config
Update to Cake.Issues 0.5.0-beta.2 and use new issue provider infrastructure
Fixes #25
=> (GH-25) Update to Cake.Issues 0.5.0-beta.2

src/Cake.Issues.DocFx/DocFxIssuesAliases.cs
=> Fix typo in alias comments

src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx.Tests/packages.config, src/Cake.Issues.DocFx/Cake.Issues.DocFx.csproj, src/Cake.Issues.DocFx/packages.config
Update to Cake.Issues 0.6.0 Beta 1
Fixes #29
=> (GH-29) Update to Cake.Issues 0.6.0 Beta 1

src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx.Tests/DocFxProviderTests.cs, src/Cake.Issues.DocFx.Tests/Testfiles/entry-with-line-0.json, src/Cake.Issues.DocFx/DocFxIssuesProvider.cs
Fix handling of issues reported for line 0
Fixes #31
=> (GH-31) Fix handling of issues reported for line 0

src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj
=> Update XUnit to 2.4.1

README.md
Add badges for AzureDevOps build status
=> Add badges for AzureDevOps build status

README.md
=> Fix links of AppVeyor badges

src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx.Tests/DocFxProviderTests.cs, src/Cake.Issues.DocFx.Tests/Testfiles/entry-of-level-suggestion.json, src/Cake.Issues.DocFx/DocFxIssuesProvider.cs
Support log messages of severity suggestions as introduced with DocFx 2.40.11
Fixes #47
=> (GH-47) Support suggestions

src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx.Tests/DocFxProviderTests.cs, src/Cake.Issues.DocFx/Cake.Issues.DocFx.csproj
Build against Cake 0.33.0
Fixes #51
=> (GH-51) Build against Cake 0.33.0

src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx.Tests/DocFxProviderTests.cs, src/Cake.Issues.DocFx.Tests/DocFxSettingsTests.cs, src/Cake.Issues.DocFx/Cake.Issues.DocFx.csproj
Update to Cake.Issues 0.7.0-beta.2 
Fixes #52
=>  (GH-52) Update to Cake.Issues 0.7.0-beta.2 

README.md, nuspec/nuget/Cake.Issues.DocFx.nuspec
Website changed to cakeissues.net
Fixes #69
=> (GH-69) Change website to cakeissues.net

src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx/Cake.Issues.DocFx.csproj, src/Cake.Issues.DocFx/DocFxIssuesProvider.cs
Update Cake.Issues to 0.8.0
Fixes #87
=> (GH-87) Update to Cake.Issues 0.8.0

docs/features.md, src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx/Cake.Issues.DocFx.csproj
Update to Cake.Issues 0.9.0 Beta 2
Fixes #114
=> (GH-114) Update to Cake.Issues 0.9.0 Beta 2

src/Cake.Issues.DocFx/DocFxIssuesSettings.cs
=> Fix typo in XML comment

README.md
=> Fix description in README

src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx/Cake.Issues.DocFx.csproj
Build against Cake.Issues 1.0 beta 1
=> Build against Cake.Issues 1.0 beta 1

src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx/Cake.Issues.DocFx.csproj
=> Update Cake.Issues v 2.0.0

.appveyor.yml, azure-pipelines.yml
Makes sure that required .NET SDK versions are available for build
=> Ensure required .NET SDK versions are available during build

src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx/Cake.Issues.DocFx.csproj
=> Build against Cake.Issues 2.0

.github/dependabot.yml
Ignore all minor updates of Cake and Cake.Issues
=> Ignore minor updates of Cake and Cake.Issues

.appveyor.yml, azure-pipelines.yml, nuspec/nuget/Cake.Issues.DocFx.nuspec, src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx/Cake.Issues.DocFx.csproj
Updates target frameworks to .NET 6 and .NET 7.
Fixes #199
=> (GH-199) Update target frameworks

src/Cake.Issues.DocFx.Tests/Cake.Issues.DocFx.Tests.csproj, src/Cake.Issues.DocFx/Cake.Issues.DocFx.csproj
Builds against Cake.Issues 3.0 Beta 2
Fixes #201
=> (GH-201) Build against Cake.Issues 3.0 Beta 2
